# Generated by Django 5.1.1 on 2024-09-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Product_image',
        ),
    ]
