# Generated by Django 5.1.1 on 2024-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
