# Generated by Django 5.1.1 on 2024-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
