# Generated by Django 5.1.1 on 2025-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_categoryoffer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
