# Generated by Django 5.1.1 on 2024-11-14 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAppSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('socialapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialapp')),
            ],
            options={
                'db_table': 'user_socialapp_site',
                'unique_together': {('socialapp', 'site')},
            },
        ),
    ]
