# Generated by Django 5.1.1 on 2024-11-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_socialappsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAppSite',
        ),
    ]
