# Generated by Django 5.1.1 on 2025-02-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_quantity_productvariant_is_default'),
        ('user', '0015_remove_wishlistitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
