# Generated by Django 5.1.1 on 2025-01-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_percentage',
        ),
    ]
